name: "Install GitHub CLI"
description: "Install gh CLI on Debian/Ubuntu runners and containers."
runs:
  using: "composite"
  steps:
    - name: Install GitHub CLI
      shell: bash
      run: |
        set -euo pipefail
        if command -v gh >/dev/null 2>&1; then
          echo "gh already installed."
          exit 0
        fi

        if ! command -v wget >/dev/null 2>&1; then
          apt-get update
          apt-get install -y wget
        fi

        mkdir -p -m 755 /etc/apt/keyrings
        out=$(mktemp)
        wget -nv -O "$out" https://cli.github.com/packages/githubcli-archive-keyring.gpg
        tee /etc/apt/keyrings/githubcli-archive-keyring.gpg < "$out" > /dev/null
        chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
        mkdir -p -m 755 /etc/apt/sources.list.d
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        apt-get update
        apt-get install -y gh
